VALID_JSON = {
    "type":"object",
    "properties":
    {
        "learn_flag":
        {
            "type":"boolean"
        },
        "hpr_prm":
        {
            "type":"object",
            "properties":
            {
                "epochs":
                {
                    "type":"integer",
                    "minimum":10
                },
                "batch_size":
                {
                  "type":"integer",
                  "minimum":10
                },
                "act_f":
                {
                    "type":"string",
                    "enum": ["identity", "relu", "sig"]
                },
                "learning_rate":
                {
                    "type":"number",
                    "minimum": 0.0,
                    "maximum":1.0
                },
                "hidden_arr":
                {
                    "type":"array",
                    "items":
                    {
                        "type":"array",
                        "minItems":2,
                        "maxItems":2,
                        "items":
                        {
                            "type":"integer"
                        }
                    }
                }
            },
            "required":["epochs", "batch_size", "act_f", "learning_rate", "hidden_arr"]
        },
        "image":
        {
            "type":"object",
            "properties":
            {
                "w":
                {
                    "type":"integer",
                    "minimum":1
                },
                "h":
                {
                    "type":"integer",
                    "minimum":1
                },
                "path":
                {
                    "type":"string"
                }
            },
            "required":["w", "h", "path"]
        }
    },
    "required":["learn_flag","hpr_prm","image"]
}